trigger:
- master
pr:
- master

pool: ubuntu18-Standard_DS2_v2

jobs:
- job: buildAndPushImage
  displayName: Build and push docker image
  timeoutInMinutes: 10
  variables:
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      repositoryPath: farfetch-data-docker-stable-we1
    ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      repositoryPath: farfetch-data-docker-beta-we1
  steps:
  - task: Docker@2
    displayName: Build and push docker image
    inputs:
      containerRegistry: artifacts-we1
      repository: $(repositoryPath)/farfetch/data-terraformprovider-ffmsgraph
      tags: |
        latest
        1.$(Build.BuildNumber)
        1.0.0
